__noadev__zrist__game__files__={};function __noadev__zrist__game__load__(){var gameScript=document.scripts.namedItem("__noadev__zrist__game__script__");var loadingHeaders=0;var loadingSize=0;var downloadedData=0;var downloadedOffset=0;var gameScriptFileSize=0;var graphicsFileSize=0;var mapsFileSize=0;var musicFileSize=0;var downloadCompleted=false;var canvas=null;var ctx=null;function prepareGame(){downloadCompleted=true;ctx.clearRect(0,0,640,480);gameScript.text=__noadev__zrist__game__files__.scriptText;}
function updateLoadingBar(){if(downloadCompleted){return;}
if(canvas==null){canvas=document.getElementById("__ZRIST__LOADING__CANVAS__");ctx=canvas.getContext("2d");ctx.fillStyle="#FFFFFF";ctx.fillRect(100,232,440,16);ctx.fillStyle="#000000";ctx.fillRect(100,232,2,2);ctx.fillRect(100,246,2,2);ctx.fillRect(538,232,2,2);ctx.fillRect(538,246,2,2);}
if(loadingSize<=0){return;}
var factor=(downloadedData+downloadedOffset)/loadingSize;if(factor>1){factor=1;}
ctx.fillStyle="#000000";ctx.fillRect(102,234,436*factor,12);ctx.fillStyle="#FFFFFF";ctx.fillRect(106,236,8,2);ctx.fillRect(104,238,2,4);}
function downloadMusicFile(){var xhr=new XMLHttpRequest();xhr.responseType="arraybuffer";xhr.open("GET","theme.ogg",true);xhr.onprogress=function(e){downloadedOffset=e.loaded;updateLoadingBar();};xhr.onload=function(e){if(xhr.status==200||xhr.status==304||xhr.status==206||(xhr.status==0&&xhr.response)){__noadev__zrist__game__files__.musicArray=xhr.response;downloadedData+=musicFileSize;downloadedOffset=0;updateLoadingBar();prepareGame();}};xhr.send();}
function downloadMapsFile(){var xhr=new XMLHttpRequest();xhr.responseType="arraybuffer";xhr.open("GET","maps.blob",true);xhr.onprogress=function(e){downloadedOffset=e.loaded;updateLoadingBar();};xhr.onload=function(e){if(xhr.status==200||xhr.status==304||xhr.status==206||(xhr.status==0&&xhr.response)){__noadev__zrist__game__files__.mapsArray=xhr.response;downloadedData+=mapsFileSize;downloadedOffset=0;updateLoadingBar();downloadMusicFile();}};xhr.send();}
function downloadGraphicsFile(){var xhr=new XMLHttpRequest();xhr.responseType="arraybuffer";xhr.open("GET","graphics.blob",true);xhr.onprogress=function(e){downloadedOffset=e.loaded;updateLoadingBar();};xhr.onload=function(e){if(xhr.status==200||xhr.status==304||xhr.status==206||(xhr.status==0&&xhr.response)){__noadev__zrist__game__files__.graphicsArray=xhr.response;downloadedData+=graphicsFileSize;downloadedOffset=0;updateLoadingBar();downloadMapsFile();}};xhr.send();}
function downloadGameScript(){var xhr=new XMLHttpRequest();xhr.responseType="text";xhr.open("GET","game.js",true);xhr.onprogress=function(e){downloadedOffset=e.loaded;updateLoadingBar();};xhr.onload=function(e){if(xhr.status==200||xhr.status==304||xhr.status==206||(xhr.status==0&&xhr.responseText)){__noadev__zrist__game__files__.scriptText=xhr.responseText;downloadedData+=gameScriptFileSize;downloadedOffset=0;updateLoadingBar();downloadGraphicsFile();}};xhr.send();}
function downloadFiles(){downloadGameScript();}
function onHeaderLoaded(){if(loadingHeaders==4){downloadFiles();}}
function getLoadSize(){var gameScriptXHR=new XMLHttpRequest();gameScriptXHR.open("HEAD","game.js",true);gameScriptXHR.responseType="text";gameScriptXHR.onreadystatechange=function(){if(gameScriptXHR.readyState==gameScriptXHR.DONE){gameScriptFileSize=parseInt(gameScriptXHR.getResponseHeader("Content-Length"));loadingSize+=gameScriptFileSize;loadingHeaders+=1;onHeaderLoaded();}};gameScriptXHR.send();var gameGraphicsXHR=new XMLHttpRequest();gameGraphicsXHR.open("HEAD","graphics.blob",true);gameGraphicsXHR.responseType="text";gameGraphicsXHR.onreadystatechange=function(){if(gameGraphicsXHR.readyState==gameGraphicsXHR.DONE){graphicsFileSize=parseInt(gameGraphicsXHR.getResponseHeader("Content-Length"));;loadingSize+=graphicsFileSize;loadingHeaders+=1;onHeaderLoaded();}};gameGraphicsXHR.send();var gameMapsXHR=new XMLHttpRequest();gameMapsXHR.open("HEAD","maps.blob",true);gameMapsXHR.responseType="text";gameMapsXHR.onreadystatechange=function(){if(gameMapsXHR.readyState==gameMapsXHR.DONE){mapsFileSize+=parseInt(gameMapsXHR.getResponseHeader("Content-Length"));loadingSize+=mapsFileSize;loadingHeaders+=1;onHeaderLoaded();}};gameMapsXHR.send();var gameMusicXHR=new XMLHttpRequest();gameMusicXHR.open("HEAD","theme.ogg",true);gameMusicXHR.responseType="text";gameMusicXHR.onreadystatechange=function(){if(gameMusicXHR.readyState==gameMusicXHR.DONE){musicFileSize=parseInt(gameMusicXHR.getResponseHeader("Content-Length"));loadingSize+=musicFileSize;loadingHeaders+=1;onHeaderLoaded();}};gameMusicXHR.send();}
function loadFiles(){loadingSize=5372630;downloadFiles();}
loadFiles();}
if(window.location.href.indexOf("kongregate.com")>=0){kongregateAPI.loadAPI(function(){kongregate=kongregateAPI.getAPI();__noadev__zrist__game__load__();});}
else{__noadev__zrist__game__load__();}