'use strict';function r(d,a,b,c){d.v.oc(d.$a,a,b,c,void 0)}function z(d,a,b,c){d.v.ua?r(d,a,b,c):d.v.pf()._OnMessageFromDOM({type:"event",component:d.$a,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function C(d,a,b){d.v.C(d.$a,a,b)}function F(d,a){for(const [b,c]of a)C(d,b,c)}function H(d){d.Qb||(d.v.Ze(d.he),d.Qb=!0)}window.ha=class{constructor(d,a){this.v=d;this.$a=a;this.Qb=!1;this.he=()=>this.xa()}jd(){}xa(){}};function J(d){-1!==d.Sa&&(self.clearTimeout(d.Sa),d.Sa=-1)}
window.Qe=class{constructor(d,a){this.Pc=d;this.Ag=a;this.Sa=-1;this.Sb=-Infinity;this.ie=()=>{this.Sa=-1;this.Sb=Date.now();this.fb=!0;this.Pc();this.fb=!1};this.Qd=this.fb=!1}c(){J(this);this.ie=this.Pc=null}};"use strict";function K(d,a){const b=a.elementId,c=d.nd(b,a);d.Y.set(b,c);a.isVisible||(c.style.display="none");c.addEventListener("focus",()=>{L(d,"elem-focused",b)});c.addEventListener("blur",()=>{L(d,"elem-blurred",b)});d.Lb&&document.body.appendChild(c)}
function N(d,a){C(d,"get-element",b=>{const c=d.Y.get(b.elementId);return a(c,b)})}function L(d,a,b,c){c||(c={});c.elementId=b;r(d,a,c)}
window.De=class extends self.ha{constructor(d,a){super(d,a);this.Y=new Map;this.Lb=!0;F(this,[["create",b=>K(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.Lb&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Lb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Lb){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.uc(c,b)}}],["focus",b=>this.Kc(b)],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);N(this,b=>b)}nd(){throw Error("required override");}uc(){throw Error("required override");}Kc(d){var a=this.Y.get(d.elementId);d.focus?a.focus():a.blur()}};
"use strict";
{const d=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(k,e){const h=document.createElement("script");h.async=!1;"module"===e&&(h.type="module");return k.Kg?new Promise(l=>{const n="c3_resolve_"+a;++a;self[n]=l;h.textContent=k.Ng+`\n\nself["${n}"]();`;document.head.appendChild(h)}):new Promise((l,n)=>{h.onload=l;h.onerror=n;h.src=k;document.head.appendChild(h)})}let c=!1,g=!1;function m(){if(!c){try{new Worker("blob://",{get type(){g=!0}})}catch(k){}c=!0}return g}
let p=new Audio;const u={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(k){k=await D(k);return(new TextDecoder("utf-8")).decode(k)}function D(k){return new Promise((e,
h)=>{const l=new FileReader;l.onload=n=>e(n.target.result);l.onerror=n=>h(n);l.readAsArrayBuffer(k)})}const w=[];let x=0;window.RealFile=window.File;const E=[],y=new Map,G=new Map;let I=0;const M=[];self.runOnStartup=function(k){if("function"!==typeof k)throw Error("runOnStartup called without a function");M.push(k)};const f=new Set(["cordova","playable-ad","instant-games"]);window.aa=class k{constructor(e){this.ua=e.Pg;this.sa=null;this.F="";this.$b=e.Mg;this.ea=e.le;this.tb={};this.La=this.sb=null;
this.Ob=[];this.hb=this.K=this.Qa=null;this.Pa=-1;this.Fg=()=>this.Mf();this.Oa=[];this.B=e.je;!this.ua||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&("module"!==this.ea||m())||(this.ua=!1);f.has(this.B)&&this.ua&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),this.ua=!1);this.Ub=this.la=null;"html5"!==this.B&&"playable-ad"!==this.B||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.C("runtime","cordova-fetch-local-file",h=>this.wf(h));this.C("runtime","create-job-worker",()=>this.xf());"cordova"===this.B?document.addEventListener("deviceready",()=>this.Cd(e)):this.Cd(e)}c(){this.vc();this.sa&&(this.sa=this.sa.onmessage=null);this.sb&&(this.sb.terminate(),this.sb=null);this.La&&(this.La.c(),this.La=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}sd(){return d&&"cordova"===this.B}nc(){return d&&f.has(this.B)||navigator.standalone}async Cd(e){if("playable-ad"===
this.B){this.la=self.c3_base64files;this.Ub={};await this.df();for(let l=0,n=e.Ta.length;l<n;++l){var h=e.Ta[l].toLowerCase();this.Ub.hasOwnProperty(h)?e.Ta[l]={Kg:!0,Ng:this.Ub[h]}:this.la.hasOwnProperty(h)&&(e.Ta[l]=URL.createObjectURL(this.la[h]))}}e.Gg?this.F=e.Gg:(h=location.origin,this.F=("null"===h?"file:///":h)+location.pathname,h=this.F.lastIndexOf("/"),-1!==h&&(this.F=this.F.substr(0,h+1)));e.Rg&&(this.tb=e.Rg);h=new MessageChannel;this.sa=h.port1;this.sa.onmessage=l=>this._OnMessageFromRuntime(l.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.If(l));this.hb=new self.Me(this);await this.hb.lc();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ua?await this.rf(e,h.port2):await this.qf(e,h.port2)}yc(e){e=this.tb.hasOwnProperty(e)?this.tb[e]:e.endsWith("/workermain.js")&&this.tb.hasOwnProperty("workermain.js")?this.tb["workermain.js"]:"playable-ad"===this.B&&this.la.hasOwnProperty(e.toLowerCase())?
this.la[e.toLowerCase()]:e;e instanceof Blob&&(e=URL.createObjectURL(e));return e}async ec(e,h,l){if(e.startsWith("blob:"))return new Worker(e,l);if(this.sd()&&"file:"===location.protocol)return e=await this.vb(this.$b+e),new Worker(URL.createObjectURL(new Blob([e],{type:"application/javascript"})),l);e=new URL(e,h);if(location.origin!==e.origin){e=await fetch(e);if(!e.ok)throw Error("failed to fetch worker script");e=await e.blob();return new Worker(URL.createObjectURL(e),l)}return new Worker(e,
l)}Aa(){return Math.max(window.innerWidth,1)}za(){return Math.max(window.innerHeight,1)}Bd(e){var h=this.hb;return{baseUrl:this.F,windowInnerWidth:this.Aa(),windowInnerHeight:this.za(),devicePixelRatio:window.devicePixelRatio,isFullscreen:k.mc(),projectData:e.Xg,scriptsType:e.le,previewImageBlobs:window.cr_previewImageBlobs||this.la,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Vg||"",exportType:e.je,isDebug:-1<self.location.search.indexOf("debug"),
ife:!!self.Wg,jobScheduler:{inputPort:h.Vc,outputPort:h.cd,maxNumWorkers:h.Cg},supportedAudioFormats:u,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$b+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.$b+"opus.wasm.wasm",isiOSCordova:this.sd(),isiOSWebView:this.nc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async rf(e,h){var l=this.yc(e.Qg);this.sb=await this.ec(l,this.F,{type:this.ea,name:"Runtime"});this.K=document.createElement("canvas");this.K.style.display=
"none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.sb.postMessage(Object.assign(this.Bd(e),{type:"init-runtime",isInWorker:!0,messagePort:h,canvas:l,workerDependencyScripts:e.hd||[],engineScripts:e.Ta,projectScripts:e.ub,mainProjectScript:e.ke,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[h,l,...O(this.hb)]);this.Ob=E.map(n=>new n(this));this.Ad();self.c3_callFunction=(n,q)=>this.Qa.sf(n,q);"preview"===this.B&&(self.goToLastErrorScript=
()=>this.oc("runtime","go-to-last-error-script"))}async qf(e,h){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Ob=E.map(q=>new q(this));this.Ad();var l=e.Ta.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(e.hd)&&l.unshift(...e.hd);l=await Promise.all(l.map(q=>this.Cc(q,this.ea)));await Promise.all(l.map(q=>b(q,this.ea)));const n=self.C3_ProjectScriptsStatus;if("module"===this.ea){l=e.ke;const q=
e.ub;for(let [v,t]of q)if(t||(t=v),v===l)try{t=await this.Cc(t,this.ea),await b(t,this.ea),"preview"!==this.B||n[v]||this.Kd(v,"main script did not run to completion")}catch(B){this.Kd(v,B)}else if("scriptsInEvents.js"===v||v.endsWith("/scriptsInEvents.js"))t=await this.Cc(t,this.ea),await b(t,this.ea)}else if(e.ub&&0<e.ub.length)try{if(await Promise.all(e.ub.map(q=>b(q[1],this.ea))),Object.values(n).some(q=>!q)){self.setTimeout(()=>this.Ld(n),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",
q);self.setTimeout(()=>this.Ld(n),100);return}"preview"===this.B&&"object"!==typeof self.Sg.Tg?(this.Ya(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(e=Object.assign(this.Bd(e),{isInWorker:!1,messagePort:h,canvas:this.K,runOnStartupFunctions:M}),this.Ed(),this.La=self.C3_CreateRuntime(e),await self.C3_InitRuntime(this.La,
e))}Ld(e){this.Ya();e=`Failed to load project script '${Object.entries(e).filter(h=>!h[1]).map(h=>h[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+e);alert(e)}Kd(e,h){this.Ya();console.error(`[Preview] Failed to load project main script (${e}): `,h);alert(`Failed to load project main script (${e}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ed(){this.Ya()}Ya(){const e=window.Hg;e&&(e.parentElement.removeChild(e),
window.Hg=null)}async xf(){const e=await P(this.hb);return{outputPort:e,transferables:[e]}}pf(){if(this.ua)throw Error("not available in worker mode");return this.La}oc(e,h,l,n,q){this.sa.postMessage({type:"event",component:e,handler:h,dispatchOpts:n||null,data:l,responseId:null},q)}td(e,h,l,n,q){const v=I++,t=new Promise((B,Z)=>{G.set(v,{resolve:B,reject:Z})});this.sa.postMessage({type:"event",component:e,handler:h,dispatchOpts:n||null,data:l,responseId:v},q);return t}["_OnMessageFromRuntime"](e){const h=
e.type;if("event"===h)return this.Cf(e);if("result"===h)this.Pf(e);else if("runtime-ready"===h)this.Qf();else if("alert-error"===h)this.Ya(),alert(e.message);else if("creating-runtime"===h)this.Ed();else throw Error(`unknown message '${h}'`);}Cf(e){const h=e.component,l=e.handler,n=e.data,q=e.responseId;if(e=y.get(h))if(e=e.get(l)){var v=null;try{v=e(n)}catch(t){console.error(`Exception in '${h}' handler '${l}':`,t);null!==q&&this.Gb(q,!1,""+t);return}if(null===q)return v;v&&v.then?v.then(t=>this.Gb(q,
!0,t)).catch(t=>{console.error(`Rejection from '${h}' handler '${l}':`,t);this.Gb(q,!1,""+t)}):this.Gb(q,!0,v)}else console.warn(`[DOM] No handler '${l}' for component '${h}'`);else console.warn(`[DOM] No event handlers for component '${h}'`)}Gb(e,h,l){let n;l&&l.transferables&&(n=l.transferables);this.sa.postMessage({type:"result",responseId:e,isOk:h,result:l},n)}Pf(e){const h=e.responseId,l=e.isOk;e=e.result;const n=G.get(h);l?n.resolve(e):n.reject(e);G.delete(h)}C(e,h,l){let n=y.get(e);n||(n=new Map,
y.set(e,n));if(n.has(h))throw Error(`[DOM] Component '${e}' already has handler '${h}'`);n.set(h,l)}static fa(e){if(E.includes(e))throw Error("DOM handler already added");E.push(e)}Ad(){for(const e of this.Ob)if("runtime"===e.$a){this.Qa=e;return}throw Error("cannot find runtime DOM handler");}If(e){this.oc("debugger","message",e)}Qf(){for(const e of this.Ob)e.jd()}static mc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ze(e){this.Oa.push(e);
this.Nc()}ag(e){e=this.Oa.indexOf(e);if(-1===e)throw Error("invalid callback");this.Oa.splice(e,1);this.Oa.length||this.vc()}Nc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Fg))}vc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}Mf(){this.Pa=-1;for(const e of this.Oa)e();this.Nc()}ya(e){this.Qa.ya(e)}Ha(e){this.Qa.Ha(e)}Mc(){this.Qa.Mc()}Bb(e){this.Qa.Bb(e)}Le(){return!!u["audio/webm; codecs=opus"]}async yg(e){e=await this.td("runtime","opus-decode",{arrayBuffer:e},
null,[e]);return new Float32Array(e)}Ke(e){return/^(?:[a-z\-]+:)?\/\//.test(e)||"data:"===e.substr(0,5)||"blob:"===e.substr(0,5)}rd(e){return!this.Ke(e)}async Cc(e,h){return"cordova"===this.B&&"module"===h&&(e.startsWith("file:")||"file:"===location.protocol&&this.rd(e))?(e.startsWith(this.F)&&(e=e.substr(this.F.length)),e=await this.vb(e),URL.createObjectURL(new Blob([e],{type:"application/javascript"}))):e}async wf(e){const h=e.filename;switch(e.as){case "text":return await this.Ce(h);case "buffer":return await this.vb(h);
default:throw Error("unsupported type");}}md(e){const h=window.cordova.file.applicationDirectory+"www/"+e.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(h,q=>{q.file(l,n)},n)})}async Ce(e){e=await this.md(e);return await A(e)}wc(){if(w.length&&!(8<=x)){x++;var e=w.shift();this.ef(e.filename,e.Og,e.Jg)}}vb(e){return new Promise((h,l)=>{w.push({filename:e,Og:n=>{x--;this.wc();h(n)},Jg:n=>{x--;this.wc();l(n)}});this.wc()})}async ef(e,h,l){try{const n=await this.md(e),q=await D(n);
h(q)}catch(n){l(n)}}async df(){const e=[];for(const [h,l]of Object.entries(this.la))e.push(this.cf(h,l));await Promise.all(e)}async cf(e,h){if("object"===typeof h)this.la[e]=new Blob([h.str],{type:h.type}),this.Ub[e]=h.str;else{let l=await this.mf(h);l||(l=this.gf(h));this.la[e]=l}}async mf(e){try{return await (await fetch(e)).blob()}catch(h){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
h),null}}gf(e){e=this.Vf(e);return this.bf(e.data,e.Lg)}Vf(e){var h=e.indexOf(",");if(0>h)throw new URIError("expected comma in data: uri");var l=e.substring(h+1);h=e.substring(5,h).split(";");e=h[0]||"";const n=h[2];l="base64"===h[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Lg:e,data:l}}bf(e,h){var l=e.length;let n=l>>2,q=new Uint8Array(l),v=new Uint32Array(q.buffer,0,n),t,B;for(B=t=0;t<n;++t)v[t]=e.charCodeAt(B++)|e.charCodeAt(B++)<<8|e.charCodeAt(B++)<<16|e.charCodeAt(B++)<<24;for(l&=
3;l--;)q[B]=e.charCodeAt(B),++B;return new Blob([q],{type:h})}}}"use strict";
{const d=self.aa;function a(f){return f.sourceCapabilities&&f.sourceCapabilities.firesTouchEvents||f.originalEvent&&f.originalEvent.sourceCapabilities&&f.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(f){return new Promise((k,e)=>{const h=document.createElement("link");h.onload=()=>k(h);h.onerror=l=>e(l);h.rel=
"stylesheet";h.href=f;document.head.appendChild(h)})}function u(f){return new Promise((k,e)=>{const h=new Image;h.onload=()=>k(h);h.onerror=l=>e(l);h.src=f})}async function A(f){f=URL.createObjectURL(f);try{return await u(f)}finally{URL.revokeObjectURL(f)}}function D(f){return new Promise((k,e)=>{let h=new FileReader;h.onload=l=>k(l.target.result);h.onerror=l=>e(l);h.readAsText(f)})}async function w(f,k,e){if(!/firefox/i.test(navigator.userAgent))return await A(f);var h=await D(f);h=(new DOMParser).parseFromString(h,
"image/svg+xml");const l=h.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),q=l.getAttribute("height");if(!n.includes("%")&&!q.includes("%"))return await A(f)}l.setAttribute("width",k+"px");l.setAttribute("height",e+"px");h=(new XMLSerializer).serializeToString(h);f=new Blob([h],{type:"image/svg+xml"});return await A(f)}function x(f){do{if(f.parentNode&&f.hasAttribute("contenteditable"))return!0;f=f.parentNode}while(f);return!1}const E=new Set(["canvas",
"body","html"]);function y(f){E.has(f.target.tagName.toLowerCase())&&f.preventDefault()}function G(f){(f.metaKey||f.ctrlKey)&&f.preventDefault()}self.C3_GetSvgImageSize=async function(f){f=await A(f);if(0<f.width&&0<f.height)return[f.width,f.height];{f.style.position="absolute";f.style.left="0px";f.style.top="0px";f.style.visibility="hidden";document.body.appendChild(f);const k=f.getBoundingClientRect();document.body.removeChild(f);return[k.width,k.height]}};self.C3_RasterSvgImageBlob=async function(f,
k,e,h,l){f=await w(f,k,e);const n=document.createElement("canvas");n.width=h;n.height=l;n.getContext("2d").drawImage(f,0,0,k,e);return n};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function M(){try{return window.parent&&window.parent.document.hasFocus()}catch(f){return!1}}d.fa(class extends self.ha{constructor(f){super(f,"runtime");this.Vd=!0;this.Ra=-1;this.ed="any";this.Md=this.Nd=!1;this.Zc=this.pb=this.Ca=null;f.C("canvas","update-size",h=>
this.Tf(h));f.C("runtime","invoke-download",h=>this.Gf(h));f.C("runtime","raster-svg-image",h=>this.Nf(h));f.C("runtime","get-svg-image-size",h=>this.Ef(h));f.C("runtime","set-target-orientation",h=>this.Rf(h));f.C("runtime","register-sw",()=>this.Of());f.C("runtime","post-to-debugger",h=>this.Gd(h));f.C("runtime","go-to-script",h=>this.Gd(h));f.C("runtime","before-start-ticking",()=>this.vf());f.C("runtime","debug-highlight",h=>this.yf(h));f.C("runtime","enable-device-orientation",()=>this.af());
f.C("runtime","enable-device-motion",()=>this.$e());f.C("runtime","add-stylesheet",h=>this.uf(h));f.C("runtime","alert",h=>this.Dc(h));f.C("runtime","hide-cordova-splash",()=>this.Ff());const k=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",h=>{const l=h.target;k.has(l.tagName.toLowerCase())||x(l)||h.preventDefault()});const e=f.K;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",y);e.addEventListener("selectstart",y);e.addEventListener("gesturehold",
y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),e.addEventListener("pointerdown",y)):e.addEventListener("touchstart",y);this.mb=0;window.addEventListener("mousedown",h=>{1===h.button&&h.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.Uf());window.addEventListener("fullscreenchange",()=>this.Fc());
window.addEventListener("webkitfullscreenchange",()=>this.Fc());window.addEventListener("mozfullscreenchange",()=>this.Fc());window.addEventListener("fullscreenerror",h=>this.Gc(h));window.addEventListener("webkitfullscreenerror",h=>this.Gc(h));window.addEventListener("mozfullscreenerror",h=>this.Gc(h));f.nc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var h=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));h="textarea"===
h?!0:"input"===h?l.has(n.type.toLowerCase()||"text"):x(n)}else h=!1}h||(document.scrollingElement.scrollTop=0)});this.Ma=new Set;this.Vb=new WeakSet;this.ra=!1}vf(){"cordova"===this.v.B?(document.addEventListener("pause",()=>this.Lc(!0)),document.addEventListener("resume",()=>this.Lc(!1))):document.addEventListener("visibilitychange",()=>this.Lc(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}jd(){window.addEventListener("focus",()=>this.Hb("window-focus"));window.addEventListener("blur",
()=>{this.Hb("window-blur",{parentHasFocus:M()});this.mb=0});window.addEventListener("keydown",k=>this.Fd("keydown",k));window.addEventListener("keyup",k=>this.Fd("keyup",k));window.addEventListener("dblclick",k=>this.Ic("dblclick",k,c));window.addEventListener("wheel",k=>this.Kf(k));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",k=>{this.zc(k);this.Xa("pointerdown",k)}),this.v.ua&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.pb=new self.Qe(()=>this.kf(),
5),this.pb.Qd=!0,window.addEventListener("pointerrawupdate",k=>this.Lf(k))):window.addEventListener("pointermove",k=>this.Xa("pointermove",k)),window.addEventListener("pointerup",k=>this.Xa("pointerup",k)),window.addEventListener("pointercancel",k=>this.Xa("pointercancel",k))):(window.addEventListener("mousedown",k=>{this.zc(k);this.Jc("pointerdown",k)}),window.addEventListener("mousemove",k=>this.Jc("pointermove",k)),window.addEventListener("mouseup",k=>this.Jc("pointerup",k)),window.addEventListener("touchstart",
k=>{this.zc(k);this.Fb("pointerdown",k)}),window.addEventListener("touchmove",k=>this.Fb("pointermove",k)),window.addEventListener("touchend",k=>this.Fb("pointerup",k)),window.addEventListener("touchcancel",k=>this.Fb("pointercancel",k)));const f=()=>this.Mc();window.addEventListener("pointerup",f,!0);window.addEventListener("touchend",f,!0);window.addEventListener("click",f,!0);window.addEventListener("keydown",f,!0);window.addEventListener("gamepadconnected",f,!0)}Hb(f,k){r(this,f,k||null,m)}Aa(){return this.v.Aa()}za(){return this.v.za()}Uf(){const f=
this.Aa(),k=this.za();this.Hb("window-resize",{innerWidth:f,innerHeight:k,devicePixelRatio:window.devicePixelRatio});this.v.nc()&&(-1!==this.Ra&&clearTimeout(this.Ra),this.Hd(f,k,0))}bg(f,k,e){-1!==this.Ra&&clearTimeout(this.Ra);this.Ra=setTimeout(()=>this.Hd(f,k,e),48)}Hd(f,k,e){const h=this.Aa(),l=this.za();this.Ra=-1;h!=f||l!=k?this.Hb("window-resize",{innerWidth:h,innerHeight:l,devicePixelRatio:window.devicePixelRatio}):10>e&&this.bg(h,l,e+1)}Rf(f){this.ed=f.targetOrientation}ug(){const f=this.ed;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(k=>console.warn("[Construct 3] Failed to lock orientation: ",k));else try{let k=!1;screen.lockOrientation?k=screen.lockOrientation(f):screen.webkitLockOrientation?k=screen.webkitLockOrientation(f):screen.mozLockOrientation?k=screen.mozLockOrientation(f):screen.msLockOrientation&&(k=screen.msLockOrientation(f));k||console.warn("[Construct 3] Failed to lock orientation")}catch(k){console.warn("[Construct 3] Failed to lock orientation: ",
k)}}Fc(){const f=d.mc();f&&"any"!==this.ed&&this.ug();r(this,"fullscreenchange",{isFullscreen:f,innerWidth:this.Aa(),innerHeight:this.za()})}Gc(f){console.warn("[Construct 3] Fullscreen request failed: ",f);r(this,"fullscreenerror",{isFullscreen:d.mc(),innerWidth:this.Aa(),innerHeight:this.za()})}Lc(f){f?this.v.vc():this.v.Nc();r(this,"visibilitychange",{hidden:f})}Fd(f,k){"Backspace"===k.key&&y(k);const e=b.get(k.code)||k.code;z(this,f,{code:e,key:k.key,which:k.which,repeat:k.repeat,altKey:k.altKey,
ctrlKey:k.ctrlKey,metaKey:k.metaKey,shiftKey:k.shiftKey,timeStamp:k.timeStamp},c)}Kf(f){r(this,"wheel",{clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,deltaX:f.deltaX,deltaY:f.deltaY,deltaZ:f.deltaZ,deltaMode:f.deltaMode,timeStamp:f.timeStamp},c)}Ic(f,k,e){a(k)||z(this,f,{button:k.button,buttons:k.buttons,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,timeStamp:k.timeStamp},e)}Jc(f,k){if(!a(k)){var e=this.mb;"pointerdown"===f&&0!==e?f="pointermove":"pointerup"===
f&&0!==k.buttons&&(f="pointermove");z(this,f,{pointerId:1,pointerType:"mouse",button:k.button,buttons:k.buttons,lastButtons:e,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:k.timeStamp},c);this.mb=k.buttons;this.Ic(k.type,k,g)}}Xa(f,k){if(this.pb&&"pointermove"!==f){var e=this.pb;e.fb||(J(e),e.Sb=Date.now())}e=0;"mouse"===k.pointerType&&(e=this.mb);z(this,f,{pointerId:k.pointerId,pointerType:k.pointerType,
button:k.button,buttons:k.buttons,lastButtons:e,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:k.width||0,height:k.height||0,pressure:k.pressure||0,tangentialPressure:k.tangentialPressure||0,tiltX:k.tiltX||0,tiltY:k.tiltY||0,twist:k.twist||0,timeStamp:k.timeStamp},c);"mouse"===k.pointerType&&(e="mousemove","pointerdown"===f?e="mousedown":"pointerup"===f&&(e="mouseup"),this.Ic(e,k,g),this.mb=k.buttons)}Lf(f){this.Zc=f;f=this.pb;if(-1===f.Sa){var k=Date.now(),e=k-f.Sb,h=f.Ag;
e>=h&&f.Qd?(f.Sb=k,f.fb=!0,f.Pc(),f.fb=!1):f.Sa=self.setTimeout(f.ie,Math.max(h-e,4))}}kf(){this.Xa("pointermove",this.Zc);this.Zc=null}Fb(f,k){for(let e=0,h=k.changedTouches.length;e<h;++e){const l=k.changedTouches[e];z(this,f,{pointerId:l.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:k.timeStamp},c)}}zc(f){window!==window.top&&window.focus();this.Dd(f.target)&&document.activeElement&&!this.Dd(document.activeElement)&&document.activeElement.blur()}Dd(f){return!f||f===document||f===window||f===document.body||"canvas"===f.tagName.toLowerCase()}af(){this.Nd||(this.Nd=!0,window.addEventListener("deviceorientation",f=>this.Af(f)),window.addEventListener("deviceorientationabsolute",f=>this.Bf(f)))}$e(){this.Md||(this.Md=!0,window.addEventListener("devicemotion",
f=>this.zf(f)))}Af(f){r(this,"deviceorientation",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp,webkitCompassHeading:f.webkitCompassHeading,webkitCompassAccuracy:f.webkitCompassAccuracy},c)}Bf(f){r(this,"deviceorientationabsolute",{absolute:!!f.absolute,alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0,timeStamp:f.timeStamp},c)}zf(f){let k=null;var e=f.acceleration;e&&(k={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var h=f.accelerationIncludingGravity;h&&(e={x:h.x||
0,y:h.y||0,z:h.z||0});h=null;const l=f.rotationRate;l&&(h={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});r(this,"devicemotion",{acceleration:k,accelerationIncludingGravity:e,rotationRate:h,interval:f.interval,timeStamp:f.timeStamp},c)}Tf(f){const k=this.v.K;k.style.width=f.styleWidth+"px";k.style.height=f.styleHeight+"px";k.style.marginLeft=f.marginLeft+"px";k.style.marginTop=f.marginTop+"px";this.Vd&&(k.style.display="",this.Vd=!1)}Gf(f){const k=f.url;f=f.filename;const e=document.createElement("a"),
h=document.body;e.textContent=f;e.href=k;e.download=f;h.appendChild(e);e.click();h.removeChild(e)}async Nf(f){var k=f.imageBitmapOpts;f=await self.C3_RasterSvgImageBlob(f.blob,f.imageWidth,f.imageHeight,f.surfaceWidth,f.surfaceHeight);k=k?await createImageBitmap(f,k):await createImageBitmap(f);return{imageBitmap:k,transferables:[k]}}async Ef(f){return await self.C3_GetSvgImageSize(f.blob)}async uf(f){await p(f.url)}Mc(){var f=[...this.Ma];this.Ma.clear();if(!this.ra)for(const k of f)(f=k.play())&&
f.catch(()=>{this.Vb.has(k)||this.Ma.add(k)})}ya(f){if("function"!==typeof f.play)throw Error("missing play function");this.Vb.delete(f);let k;try{k=f.play()}catch(e){this.Ma.add(f);return}k&&k.catch(()=>{this.Vb.has(f)||this.Ma.add(f)})}Ha(f){this.Ma.delete(f);this.Vb.add(f)}Bb(f){this.ra=!!f}Ff(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}yf(f){if(f.show){this.Ca||(this.Ca=document.createElement("div"),this.Ca.id="inspectOutline",document.body.appendChild(this.Ca));
var k=this.Ca;k.style.display="";k.style.left=f.left-1+"px";k.style.top=f.top-1+"px";k.style.width=f.width+2+"px";k.style.height=f.height+2+"px";k.textContent=f.name}else this.Ca&&(this.Ca.style.display="none")}Of(){window.C3_RegisterSW&&window.C3_RegisterSW()}Gd(f){window.c3_postToMessagePort&&(f.from="runtime",window.c3_postToMessagePort(f))}sf(f,k){return this.v.td(this.$a,"js-invoke-function",{name:f,params:k},void 0,void 0)}Dc(f){alert(f.message)}})}"use strict";
function O(d){return[d.Vc,d.cd]}async function P(d){const a=d.Xd.length;var b=d.Zb.yc("jobworker.js");b=await d.Zb.ec(b,d.F,{name:"JobWorker"+a});const c=new MessageChannel,g=new MessageChannel;d.Rc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":g.port2},[c.port2,g.port2]);d.Xd.push(b);return g.port1}
self.Me=class{constructor(d){this.Zb=d;this.F=d.F;this.F="preview"===d.B?this.F+"c3/workers/":this.F+d.$b;this.Cg=Math.min(navigator.hardwareConcurrency||2,16);this.Rc=null;this.Xd=[];this.cd=this.Vc=null}async lc(){if(this.zg)throw Error("already initialised");this.zg=!0;var d=this.Zb.yc("dispatchworker.js");this.Rc=await this.Zb.ec(d,this.F,{name:"DispatchWorker"});d=new MessageChannel;this.Vc=d.port1;this.Rc.postMessage({type:"_init","in-port":d.port2},[d.port2]);this.cd=await P(this)}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.aa({Pg:!0,Qg:"workermain.js",Ta:["scripts/c3runtime.js"],ub:[],ke:"",le:"module",Mg:"scripts/",hd:["box2d.wasm.js"],je:"html5"}));"use strict";
{const d=180/Math.PI;self.ga=class extends self.ha{constructor(a){super(a,"audio");this.Nb=this.f=null;this.Pb=this.Uc=!1;this.ta=()=>this.vg();this.ca=[];this.D=[];this.ka=null;this.Yd="";this.Zd=-1;this.ob=new Map;this.$c=1;this.ra=!1;this.fd=0;this.bc=1;this.Sc=0;this.ae="HRTF";this.Rd="inverse";this.be=600;this.$d=1E4;this.de=1;this.Td=this.dd=!1;this.ge=this.v.Le();this.da=new Map;this.Ja=new Set;this.Wc=!1;this.ad="";this.Da=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Jf(b,c);this.Mb=null;
self.C3Audio_GetOutputStream=()=>this.Df();self.C3Audio_DOMInterface=this;F(this,[["create-audio-context",b=>this.ff(b)],["play",b=>this.Wf(b)],["stop",b=>this.sg(b)],["stop-all",()=>this.tg()],["set-paused",b=>this.lg(b)],["set-volume",b=>this.qg(b)],["fade-volume",b=>this.lf(b)],["set-master-volume",b=>this.jg(b)],["set-muted",b=>this.kg(b)],["set-silent",b=>this.ng(b)],["set-looping",b=>this.ig(b)],["set-playback-rate",b=>this.mg(b)],["seek",b=>this.cg(b)],["preload",b=>this.Xf(b)],["unload",b=>
this.wg(b)],["unload-all",()=>this.xg()],["set-suspended",b=>this.og(b)],["add-effect",b=>this.yd(b)],["set-effect-param",b=>this.fg(b)],["remove-effects",b=>this.Zf(b)],["tick",b=>this.Sf(b)],["load-state",b=>this.Hf(b)]])}async ff(a){a.isiOSCordova&&(this.dd=!0);this.fd=a.timeScaleMode;this.ae=["equalpower","HRTF","soundfield"][a.panningModel];this.Rd=["linear","inverse","exponential"][a.distanceModel];this.be=a.refDistance;this.$d=a.maxDistance;this.de=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ge||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.zd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.zd()};this.Nb=this.f.createGain();this.Nb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.fc();try{await Promise.all(a.preloadList.map(c=>this.Db(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}zd(){this.Pb||(this.Uc=!1,window.addEventListener("pointerup",this.ta,!0),window.addEventListener("touchend",this.ta,!0),window.addEventListener("click",this.ta,!0),window.addEventListener("keydown",this.ta,!0),this.Pb=!0)}hf(){this.Pb&&(this.Uc=!0,window.removeEventListener("pointerup",this.ta,!0),window.removeEventListener("touchend",
this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",this.ta,!0),this.Pb=!1)}vg(){if(!this.Uc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.hf()}}W(){return this.f}fc(){return this.f.currentTime}va(){return this.Nb}pd(a){return(a=this.da.get(a.toLowerCase()))?a[0].P():this.va()}me(a,b){a=a.toLowerCase();let c=this.da.get(a);
c||(c=[],this.da.set(a,c));b.hg(c.length);b.pg(a);c.push(b);this.Jd(a)}Jd(a){let b=this.va();const c=this.da.get(a);if(c&&c.length){b=c[0].P();for(let g=0,m=c.length;g<m;++g){const p=c[g];g+1===m?p.S(this.va()):p.S(c[g+1].P())}}for(const g of this.pa(a))g.Re(b);this.Da&&this.ad===a&&(this.Da.disconnect(),this.Da.connect(b))}xb(){return this.$c}yb(){return this.ra}gg(){this.Td=!0}Fe(a,b){return b?this.v.yg(a).then(c=>{const g=this.f.createBuffer(1,c.length,48E3);g.getChannelData(0).set(c);return g}):
new Promise((c,g)=>{this.f.decodeAudioData(a,c,g)})}ya(a){this.v.ya(a)}Ha(a){this.v.Ha(a)}ud(a){let b=0;for(let c=0,g=this.D.length;c<g;++c){const m=this.D[c];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Se(){let a=0;for(let b=0,c=this.ca.length;b<c;++b){const g=this.ca[b];this.ca[a]=g;g.wa()?g.c():++a}this.ca.length=a}*pa(a){if(a)for(const b of this.D)self.ga.Ge(b.$,a)&&(yield b);else this.ka&&!this.ka.T()&&(yield this.ka)}async Db(a,b,c,g,m){for(const p of this.ca)if(p.Va()===b)return await Q(p),
p;if(m)return null;g&&(this.dd||this.Td)&&this.Se();m="audio/webm; codecs=opus"===c&&!this.ge;g&&m&&this.gg();a=!g||this.dd||m?new self.Ae(this,a,b,c,g,m):new self.ye(this,a,b,c,g);this.ca.push(a);await Q(a);return a}async xc(a,b,c,g,m){for(const p of this.D)if(p.Va()===b&&(p.dc()||m))return p.Ue(g),p;a=await this.Db(a,b,c,m);g="html5"===a.Oc?new self.ze(a.i,a,g):new self.Be(a.i,a,g);this.D.push(g);return g}Ye(a){let b=this.ob.get(a);if(!b){let c=null;b={gd:0,promise:new Promise(g=>c=g),resolve:c};
this.ob.set(a,b)}b.gd++}$f(a){const b=this.ob.get(a);if(!b)throw Error("expected pending tag");b.gd--;0===b.gd&&(b.resolve(),this.ob.delete(a))}tc(a){a||(a=this.Yd);return(a=this.ob.get(a))?a.promise:Promise.resolve()}Eb(){if(0<this.Ja.size)H(this);else for(const a of this.D)if(a.qd()){H(this);break}}xa(){for(var a of this.Ja)a.xa();a=this.fc();for(var b of this.D)b.xa(a);b=this.D.filter(c=>c.qd()).map(c=>c.Ua());r(this,"state",{tickCount:this.Zd,audioInstances:b,analysers:[...this.Ja].map(c=>c.Ie())});
0===b.length&&0===this.Ja.size&&this.Qb&&(this.v.ag(this.he),this.Qb=!1)}pc(a,b,c){r(this,"trigger",{type:a,tag:b,aiid:c})}async Wf(a){const b=a.originalUrl,c=a.url,g=a.type,m=a.isMusic,p=a.tag,u=a.isLooping,A=a.vol,D=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Yd=p;this.Ye(p);try{this.ka=await this.xc(b,c,g,p,m),w?(this.ka.Ab(!0),this.ka.Te(w.x,
w.y,w.angle,w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this.ka.Ve(w.uid)):this.ka.Ab(!1),this.ka.Play(u,A,D,x)}catch(E){console.error("[Construct 3] Audio: error starting playback: ",E);return}finally{this.$f(p)}H(this)}sg(a){a=a.tag;for(const b of this.pa(a))b.qa()}tg(){for(const a of this.D)a.qa()}lg(a){const b=a.tag;a=a.paused;for(const c of this.pa(b))a?c.Wa():c.zb();this.Eb()}qg(a){const b=a.tag;a=a.vol;for(const c of this.pa(b))c.Cb(a)}async lf(a){const b=a.tag,c=a.vol,
g=a.duration;a=a.stopOnEnd;await this.tc(b);for(const m of this.pa(b))m.He(c,g,a);this.Eb()}jg(a){this.$c=a.vol;for(const b of this.D)b.Jb()}kg(a){const b=a.tag;a=a.isMuted;for(const c of this.pa(b))c.vd(a)}ng(a){this.ra=a.isSilent;this.v.Bb(this.ra);for(const b of this.D)b.Ib()}ig(a){const b=a.tag;a=a.isLooping;for(const c of this.pa(b))c.rc(a)}async mg(a){const b=a.tag;a=a.rate;await this.tc(b);for(const c of this.pa(b))c.xd(a)}async cg(a){const b=a.tag;a=a.pos;await this.tc(b);for(const c of this.pa(b))c.qc(a)}async Xf(a){const b=
a.originalUrl,c=a.url,g=a.type;a=a.isMusic;try{await this.xc(b,c,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async wg(a){if(a=await this.Db("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ca.indexOf(a),-1!==a&&this.ca.splice(a,1)}xg(){for(const a of this.ca)a.c();this.ca.length=0}og(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.sc(a);a&&this.f.suspend&&this.f.suspend()}Sf(a){this.bc=a.timeScale;this.Sc=a.gameTime;this.Zd=a.tickCount;if(0!==
this.fd)for(var b of this.D)b.Ia();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const g of this.D)g.ja===a&&g.wd(c.x,c.y,c.angle)}}async yd(a){var b=a.type;const c=a.tag;var g=a.params;if("filter"===b)g=new self.se(this,...g);else if("delay"===b)g=new self.qe(this,...g);else if("convolution"===b){b=null;try{b=await this.Db(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.pe(this,b.ba,...g);g.dg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.te(this,...g);else if("phaser"===b)g=new self.ve(this,...g);else if("gain"===b)g=new self.ue(this,...g);else if("tremolo"===b)g=new self.xe(this,...g);else if("ringmod"===b)g=new self.we(this,...g);else if("distortion"===b)g=new self.re(this,...g);else if("compressor"===b)g=new self.oe(this,...g);else if("analyser"===b)g=new self.ne(this,...g);else throw Error("invalid effect type");this.me(c,
g);this.Id()}fg(a){const b=a.index,c=a.param,g=a.value,m=a.ramp,p=a.time;a=this.da.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,g,m,p),this.Id())}Zf(a){a=a.tag.toLowerCase();const b=this.da.get(a);if(b&&b.length){for(const c of b)c.c();this.da.delete(a);this.Jd(a)}}Xe(a){this.Ja.add(a);this.Eb()}Yf(a){this.Ja.delete(a)}Id(){this.Wc||(this.Wc=!0,Promise.resolve().then(()=>this.jf()))}jf(){const a={};for(const [b,c]of this.da)a[b]=c.map(g=>g.Ua());r(this,"fxstate",{fxstate:a});this.Wc=!1}async Hf(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.wa()&&1===b||(c.wa()||2!==b)&&c.qa();for(const g of this.da.values())for(const m of g)m.c();this.da.clear();this.bc=a.timeScale;this.Sc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.ra=a.isSilent;this.v.Bb(this.ra);this.$c=a.masterVolume;c=[];for(const g of Object.values(a.effects))c.push(Promise.all(g.map(m=>this.yd(m))));await Promise.all(c);await Promise.all(a.playing.map(g=>this.tf(g,b)));this.Eb()}async tf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,u=a.tag,A=a.isLooping,D=a.volume,w=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.xc(c,g,m,u,p)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Pe(a.pan);b.Play(A,D,w,0);a.isPlaying||b.Wa();b.Bc(a)}}}Jf(a,b){this.Da&&this.Da.disconnect();this.ad=b.toLowerCase();this.Da=this.f.createMediaStreamSource(a);this.Da.connect(this.pd(this.ad))}Df(){this.Mb||(this.Mb=this.f.createMediaStreamDestination(),
this.Nb.connect(this.Mb));return this.Mb.stream}static Ge(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static We(a){return a*d}static Ee(a){return Math.pow(10,a/20)}static od(a){return Math.max(Math.min(self.ga.Ee(a),1),0)}static Oe(a){return Math.log(a)/Math.log(10)*20}static Ne(a){return self.ga.Oe(Math.max(Math.min(a,1),0))}static Ig(a,b){return 1-Math.exp(-b*a)}};self.aa.fa(self.ga)}"use strict";function Q(d){d.Tb||(d.Tb=d.Ac());return d.Tb}
self.kd=class{constructor(d,a,b,c,g){this.i=d;this.Eg=a;this.Fa=b;this.R=c;this.Bg=g;this.Oc="";this.Tb=null}c(){this.Tb=this.i=null}Ac(){}W(){return this.i.W()}ic(){return this.Eg}Va(){return this.Fa}hc(){return this.R}wa(){return this.Bg}ia(){}};"use strict";
self.ye=class extends self.kd{constructor(d,a,b,c,g){super(d,a,b,c,g);this.Oc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.ib=this.jb=null;this.J.addEventListener("canplaythrough",()=>!0);this.nb=this.W().createGain();this.lb=null;this.J.addEventListener("canplay",()=>{this.jb&&(this.jb(),this.ib=this.jb=null);!this.lb&&this.J&&(this.lb=this.W().createMediaElementSource(this.J),this.lb.connect(this.nb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Fa}' error: `,m);this.ib&&(this.ib(m),this.ib=this.jb=null)})}c(){this.i.ud(this);this.nb.disconnect();this.nb=null;this.lb.disconnect();this.lb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Ac(){return new Promise((d,a)=>{this.jb=d;this.ib=a;this.J.src=this.Fa})}O(){return this.J}ia(){return this.J.duration}};"use strict";
async function ba(d){if(d.Ba)return d.Ba;var a=d.i.v;if("cordova"===a.B&&a.rd(d.Fa)&&"file:"===location.protocol)d.Ba=await a.vb(d.Fa);else{a=await fetch(d.Fa);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);d.Ba=await a.arrayBuffer()}}async function ca(d){if(d.ba)return d.ba;d.ba=await d.i.Fe(d.Ba,d.Dg);d.Ba=null}
self.Ae=class extends self.kd{constructor(d,a,b,c,g,m){super(d,a,b,c,g);this.Oc="webaudio";this.ba=this.Ba=null;this.Dg=!!m}c(){this.i.ud(this);this.ba=this.Ba=null;super.c()}async Ac(){try{await ba(this),await ca(this)}catch(d){console.error(`[Construct 3] Failed to load audio '${this.Fa}': `,d)}}ia(){return this.ba?this.ba.duration:0}};"use strict";
{let d=0;self.ld=class{constructor(a,b,c){this.i=a;this.L=b;this.$=c;this.Kb=d++;this.M=this.W().createGain();this.M.connect(this.va());this.A=null;this.gb=!1;this.na=[0,0,0];this.ma=[0,0,0];this.H=!0;this.V=this.oa=this.G=!1;this.rb=1;this.Ka=!1;this.Z=1;a=this.i.fd;this.Yc=1===a&&!this.wa()||2===a;this.cb=this.ja=-1;this.fe=!1}c(){this.L=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.M.disconnect();this.M=null}W(){return this.i.W()}va(){return this.i.pd(this.$)}xb(){return this.i.xb()}wb(){return this.Yc?
this.i.Sc:performance.now()/1E3}ic(){return this.L.ic()}Va(){return this.L.Va()}hc(){return this.L.hc()}wa(){return this.L.wa()}Ue(a){this.$=a}T(){}dc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}qd(){return!this.H&&!this.T()}Ga(){}ia(){return this.L.ia()}Play(){}qa(){}Wa(){}zb(){}Cb(a){this.rb=a;this.M.gain.cancelScheduledValues(0);this.cb=-1;this.M.gain.value=this.jc()}He(a,b,c){if(!this.Ka){a*=this.xb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.fc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.rb=a;this.cb=b;this.fe=c}}Jb(){this.Cb(this.rb)}xa(a){-1!==this.cb&&a>=this.cb&&(this.cb=-1,this.fe&&this.qa(),this.i.pc("fade-ended",this.$,this.Kb))}jc(){const a=this.rb*this.xb();return isFinite(a)?a:0}vd(a){a=!!a;this.Ka!==a&&(this.Ka=a,this.Ib())}yb(){return this.i.yb()}Ib(){}rc(){}xd(a){this.Z!==a&&(this.Z=a,this.Ia())}Ia(){}qc(){}sc(){}Ab(a){a=!!a;this.gb!==a&&((this.gb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.ae,this.A.distanceModel=
this.i.Rd,this.A.refDistance=this.i.be,this.A.maxDistance=this.i.$d,this.A.rolloffFactor=this.i.de),this.M.disconnect(),this.M.connect(this.A),this.A.connect(this.va())):(this.A.disconnect(),this.M.disconnect(),this.M.connect(this.va())))}Te(a,b,c,g,m,p){this.gb&&(this.wd(a,b,c),a=self.ga.We,this.A.coneInnerAngle=a(g),this.A.coneOuterAngle=a(m),this.A.coneOuterGain=p)}wd(a,b,c){this.gb&&(this.na[0]=a,this.na[1]=b,this.na[2]=0,this.ma[0]=Math.cos(c),this.ma[1]=Math.sin(c),this.ma[2]=0,this.A.setPosition(...this.na),
this.A.setOrientation(...this.ma))}Ve(a){this.ja=a}kc(){}Re(a){const b=this.A||this.M;b.disconnect();b.connect(a)}Ua(){return{aiid:this.Kb,tag:this.$,duration:this.ia(),volume:this.rb,isPlaying:this.IsPlaying(),playbackTime:this.Ga(),playbackRate:this.Z,uid:this.ja,bufferOriginalUrl:this.ic(),bufferUrl:"",bufferType:this.hc(),isMusic:this.wa(),isLooping:this.V,isMuted:this.Ka,resumePosition:this.kc(),pan:this.Je()}}Bc(a){this.xd(a.playbackRate);this.vd(a.isMuted)}Je(){if(!this.A)return null;const a=
this.A;return{pos:this.na,orient:this.ma,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.ja}}Pe(a){if(a){this.Ab(!0);a=this.A;var b=a.pos;this.na[0]=b[0];this.na[1]=b[1];this.na[2]=b[2];b=a.orient;this.ma[0]=b[0];this.ma[1]=b[1];this.ma[2]=b[2];a.setPosition(...this.na);a.setOrientation(...this.ma);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.ja=a.uid}else this.Ab(!1)}}}"use strict";
self.ze=class extends self.ld{constructor(d,a,b){super(d,a,b);this.L.nb.connect(this.M);this.L.onended=()=>this.Ec()}c(){this.qa();this.L.nb.disconnect();super.c()}O(){return this.L.O()}Ec(){this.H=!0;this.ja=-1;this.i.pc("ended",this.$,this.Kb)}T(){return this.O().ended}dc(){return this.H?!0:this.T()}Ga(d){let a=this.O().currentTime;d&&(a*=this.Z);this.V||(a=Math.min(a,this.ia()));return a}Play(d,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==d&&(c.loop=d);this.Cb(a);c.muted&&
(c.muted=!1);if(c.currentTime!==b)try{c.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Va()}' to position '${b}': `,g)}this.i.ya(c);this.G=this.H=!1;this.V=d;this.Z=1}qa(){const d=this.O();d.paused||d.pause();this.i.Ha(d);this.H=!0;this.G=!1;this.ja=-1}Wa(){if(!(this.G||this.H||this.T())){var d=this.O();d.paused||d.pause();this.i.Ha(d);this.G=!0}}zb(){!this.G||this.H||this.T()||(this.i.ya(this.O()),this.G=!1)}Ib(){this.O().muted=this.Ka||this.yb()}rc(d){d=!!d;
this.V!==d&&(this.V=d,this.O().loop=d)}Ia(){let d=this.Z;this.Yc&&(d*=this.i.bc);try{this.O().playbackRate=d}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${d}':`,a)}}qc(d){if(!this.H&&!this.T())try{this.O().currentTime=d}catch(a){console.warn(`[Construct 3] Error seeking audio to '${d}': `,a)}}kc(){return this.Ga()}sc(d){d?this.IsPlaying()?(this.O().pause(),this.oa=!0):this.oa=!1:this.oa&&(this.i.ya(this.O()),this.oa=!1)}};"use strict";
function R(d){d.j&&d.j.disconnect();d.j=null;d.Za=null}
self.Be=class extends self.ld{constructor(d,a,b){super(d,a,b);this.j=null;this.Wb=c=>this.Ec(c);this.Tc=!0;this.Za=null;this.N=this.ac=0;this.bd=1}c(){this.qa();R(this);this.Wb=null;super.c()}Ec(d){this.G||this.oa||d.target!==this.Za||(this.H=this.Tc=!0,this.ja=-1,R(this),this.i.pc("ended",this.$,this.Kb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Tc}dc(){return!this.j||this.H?!0:this.T()}Ga(d){let a;a=this.G?this.N:this.wb()-this.ac;d&&(a*=this.Z);this.V||(a=Math.min(a,this.ia()));return a}Play(d,
a,b,c){this.bd=1;this.Cb(a);R(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.ba;this.j.connect(this.M);this.Za=this.j;this.j.onended=this.Wb;this.j.loop=d;this.j.start(c,b);this.G=this.H=this.Tc=!1;this.V=d;this.Z=1;this.ac=this.wb()-b}qa(){if(this.j)try{this.j.stop(0)}catch(d){}this.H=!0;this.G=!1;this.ja=-1}Wa(){this.G||this.H||this.T()||(this.N=this.Ga(!0),this.V&&(this.N%=this.ia()),this.G=!0,this.j.stop(0))}zb(){!this.G||this.H||this.T()||(R(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.ba,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Jb(),this.Ia(),this.ac=this.wb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.G=!1)}jc(){return super.jc()*this.bd}Ib(){this.bd=this.Ka||this.yb()?0:1;this.Jb()}rc(d){d=!!d;this.V!==d&&(this.V=d,this.j&&(this.j.loop=d))}Ia(){let d=this.Z;this.Yc&&(d*=this.i.bc);this.j&&(this.j.playbackRate.value=d)}qc(d){this.H||this.T()||(this.G?this.N=d:(this.Wa(),this.N=d,this.zb()))}kc(){return this.N}sc(d){d?
this.IsPlaying()?(this.oa=!0,this.N=this.Ga(!0),this.V&&(this.N%=this.ia()),this.j.stop(0)):this.oa=!1:this.oa&&(R(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.ba,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Wb,this.j.loop=this.V,this.Jb(),this.Ia(),this.ac=this.wb()-this.N/(this.Z||.001),this.j.start(0,this.N),this.oa=!1)}Bc(d){super.Bc(d);this.N=d.resumePosition}};"use strict";
{class d{constructor(a){this.i=a;this.f=a.W();this.Ud=-1;this.R=this.$="";this.g=null}c(){this.f=null}hg(a){this.Ud=a}pg(a){this.$=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(c){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Ua(){return{type:this.R,tag:this.$,params:this.g}}}
self.se=class extends d{constructor(a,b,c,g,m,p,u){super(a);this.R="filter";this.g=[b,c,g,m,p,u];this.l=this.o();this.b=this.o();this.b.gain.value=u;this.a=this.o();this.a.gain.value=1-u;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=g;this.u.Q.value=m;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,g);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,g)}}};self.qe=class extends d{constructor(a,b,c,g){super(a);this.R="delay";this.g=[b,c,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.kb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.bb=this.o();this.bb.gain.value=c;this.l.connect(this.kb);this.l.connect(this.a);this.kb.connect(this.b);this.kb.connect(this.U);this.U.connect(this.bb);this.bb.connect(this.kb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.kb.disconnect();this.U.disconnect();this.bb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){const m=self.ga.od;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,g);this.m(this.a.gain,1-b,c,g);break;case 4:this.g[1]=m(b);this.m(this.bb.gain,m(b),c,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,g)}}};self.pe=class extends d{constructor(a,b,c,g){super(a);this.R="convolution";this.g=[c,g];this.Pd=this.Od="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.ab=this.f.createConvolver();this.ab.normalize=c;this.ab.buffer=b;this.l.connect(this.ab);this.l.connect(this.a);this.ab.connect(this.b)}c(){this.l.disconnect();this.ab.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}dg(a,b){this.Od=a;this.Pd=b}Ua(){const a=
super.Ua();a.bufferOriginalUrl=this.Od;a.bufferUrl="";a.bufferType=this.Pd;return a}};self.te=class extends d{constructor(a,b,c,g,m,p){super(a);this.R="flanger";this.g=[b,c,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.eb=this.o();this.eb.gain.value=m;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.eb);this.eb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.eb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,c,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,g);break;case 8:this.g[3]=b/100,this.m(this.eb.gain,b/100,c,g)}}};self.ve=class extends d{constructor(a,b,c,g,m,p,u){super(a);this.R="phaser";this.g=[b,c,g,m,p,u];this.l=this.o();this.a=this.o();this.a.gain.value=1-u/2;this.b=this.o();this.b.gain.value=u/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,g);this.m(this.a.gain,1-b/2,c,g);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,g);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,g);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,c,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,g)}}};self.ue=class extends d{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){const m=self.ga.od;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),c,g)}}};self.xe=class extends d{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=c/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,g);this.m(this.I.gain,b/2,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.we=class extends d{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.qb=this.o();this.qb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.qb.gain);this.s.start(0);this.l.connect(this.qb);this.l.connect(this.a);this.qb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.qb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,g);
this.m(this.a.gain,1-b,c,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,g)}}};self.re=class extends d{constructor(a,b,c,g,m,p){super(a);this.R="distortion";this.g=[b,c,g,m,p];this.l=this.o();this.Yb=this.o();this.Xb=this.o();this.eg(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.cc=this.f.createWaveShaper();this.Qc=new Float32Array(65536);this.nf(b,c);this.cc.curve=this.Qc;this.l.connect(this.Yb);this.l.connect(this.a);this.Yb.connect(this.cc);this.cc.connect(this.Xb);
this.Xb.connect(this.b)}c(){this.l.disconnect();this.Yb.disconnect();this.cc.disconnect();this.Xb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}eg(a,b){.01>a&&(a=.01);this.Yb.gain.value=a;this.Xb.gain.value=Math.pow(1/a,.6)*b}nf(a,b){for(let c=0;32768>c;++c){let g=c/32768;g=this.rg(g,a,b);this.Qc[32768+c]=g;this.Qc[32768-c-1]=-g}}rg(a,b,c){c=1.05*c*b-b;const g=0>a?-a:a;return(g<b?g:b+c*self.ga.Ig(g-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,c,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,g),this.m(this.a.gain,1-b,c,g)}}};self.oe=class extends d{constructor(a,b,c,g,m,p){super(a);this.R="compressor";this.g=[b,c,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ne=class extends d{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Sd=new Float32Array(this.h.frequencyBinCount);this.ee=new Uint8Array(b);this.ce=this.Na=0;this.i.Xe(this)}c(){this.i.Yf(this);this.h.disconnect();super.c()}xa(){this.h.getFloatFrequencyData(this.Sd);this.h.getByteTimeDomainData(this.ee);const a=this.h.fftSize;let b=this.Na=0;for(var c=0;c<a;++c){let g=(this.ee[c]-128)/128;0>g&&(g=-g);
this.Na<g&&(this.Na=g);b+=g*g}c=self.ga.Ne;this.Na=c(this.Na);this.ce=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ie(){return{tag:this.$,index:this.Ud,peak:this.Na,rms:this.ce,binCount:this.h.frequencyBinCount,freqBins:this.Sd}}}}"use strict";function da(d){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>r(d,"sw-message",a.data))}
function ea(d){d=d.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(d).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(d):screen.webkitLockOrientation?a=screen.webkitLockOrientation(d):screen.mozLockOrientation?a=screen.mozLockOrientation(d):screen.msLockOrientation&&(a=screen.msLockOrientation(d));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.aa.fa(class extends self.ha{constructor(d){super(d,"browser");this.B="";F(this,[["get-initial-state",a=>this.Hc(a)],["ready-for-sw-messages",()=>da(this)],["alert",a=>this.Dc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Kc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>ea(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?
screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===b)window.forward();else if("home"===b)window.home();else if("reload"===b)location.reload();
else if("url"===b){b=a.url;var c=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Ug||(2===c?window.top.location=b:1===c?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,c=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?
Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,c))}],["request-fullscreen",a=>{{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==
typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{r(this,"online-state",{isOnline:!0})});window.addEventListener("offline",
()=>{r(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{r(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{r(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;r(this,"backbutton")})}Hc(d){this.B=d.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,
isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}Dc(d){alert(d.message)}Kc(d){d=d.isFocus;if("nwjs"===this.B){const a="nwjs"===this.B?nw.Window.get():null;d?a.focus():a.blur()}else d?window.focus():window.blur()}});"use strict";function fa(d){const a=d.method;setTimeout(()=>S()[a](),100)}
function S(){return nw.Window.get()}function T(d,a){const b=document.createElement("input");b.type="file";b.style.display="none";b.id=d;a&&b.setAttribute(a,"");document.body.appendChild(b);return b}function U(){return nw.Clipboard.get().get()||""}function V(){const d=S();return{"window-title":d.title||"","window-x":d.x,"window-y":d.y,"window-width":d.width,"window-height":d.height}}
self.aa.fa(class extends self.ha{constructor(d){super(d,"nwjs");this.Rb=!1;F(this,[["init",()=>this.lc()],["show-open-dlg",a=>{if(this.Rb){var b=document.getElementById("c3nwOpenFileDialog");b.setAttribute("accept",a.accept);b.click()}}],["show-folder-dlg",()=>{this.Rb&&document.getElementById("c3nwChooseFolderDialog").click()}],["show-save-dlg",a=>{if(this.Rb){var b=document.getElementById("c3nwSaveDialog");b.setAttribute("accept",a.accept);b.click()}}],["set-title",a=>{a=a.title;document.title=
a;S().title=a}],["set-window-x",a=>{S().x=a.x}],["set-window-y",a=>{S().y=a.y}],["set-window-width",a=>{{const b=S();a=a.width;b.setInnerWidth?b.setInnerWidth(a):b.width=a}}],["set-window-height",a=>{{const b=S();a=a.height;b.setInnerHeight?b.setInnerHeight(a):b.height=a}}],["window-cmd",a=>fa(a)],["window-attention",a=>{S().requestAttention(a.request)}],["set-window-max-size",a=>{S().setMaximumSize(a.width,a.height)}],["set-window-min-size",a=>{S().setMinimumSize(a.width,a.height)}],["set-window-resizable",
a=>{S().setResizable(a.resizable)}],["set-window-always-top",a=>{S().setAlwaysOnTop(a.top)}],["shell-cmd",a=>{nw.Shell[a.method](a.arg)}],["set-clipboard",a=>{nw.Clipboard.get().set(a.text)}],["clear-clipboard",()=>{nw.Clipboard.get().clear()}]])}lc(){this.Rb=!0;nw.App.clearCache();window.addEventListener("dragover",m=>m.preventDefault());window.addEventListener("drop",m=>{{m.preventDefault();m=m.dataTransfer.files;const p=[];for(let u=0,A=m.length;u<A;++u)p.push(m[u].path);r(this,"drop",{filePaths:p})}return!1});
const d=T("c3nwOpenFileDialog");d.onchange=()=>{r(this,"open-dlg",{chosenPath:d.value});try{d.value=null}catch(m){}};d.oncancel=()=>{r(this,"open-dlg-cancel")};const a=T("c3nwChooseFolderDialog","nwdirectory");a.onchange=()=>{r(this,"folder-dlg",{chosenPath:a.value});try{a.value=null}catch(m){}};a.oncancel=()=>{r(this,"folder-dlg-cancel")};const b=T("c3nwSaveDialog","nwsaveas");b.onchange=()=>{r(this,"save-dlg",{chosenPath:b.value});try{b.value=null}catch(m){}};b.oncancel=()=>{r(this,"save-dlg-cancel")};
const c=S();c.on("move",()=>{r(this,"window-change",V())});c.on("resize",()=>{r(this,"window-change",V())});let g=U();setInterval(()=>{const m=U();g!==m&&(g=m,r(this,"clipboard-change",{"clipboard-text":m}))},1E3);return Object.assign({argv:nw.App.argv,"clipboard-text":g},V())}});"use strict";
async function ia(d){var a=W(d.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:d.duration,startDelay:0,weakMagnitude:d.weakMag,strongMagnitude:d.strongMag})}catch(b){console.warn("[Gamepad] Failed to vibrate gamepad: ",b)}}function X(){return Array.from(navigator.getGamepads()).filter(d=>d&&d.connected)}function W(d){for(const a of X())if(a.index===d)return a;return null}
self.aa.fa(class extends self.ha{constructor(d){super(d,"gamepad");this.Wd=!!navigator.getGamepads;this.Xc=!1;C(this,"is-supported",()=>this.Wd);C(this,"ready",()=>{this.Xc=!0;for(const a of X())r(this,"gamepad-connected",{index:a.index,id:a.id});this.Wd&&H(this)});C(this,"vibrate",a=>ia(a));C(this,"reset-vibrate",a=>{(a=W(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.Xc&&(a=a.gamepad,r(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.Xc&&r(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of X()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}})}xa(){var d=X();d.length&&(d=d.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(b=>({pressed:b.pressed,value:b.value})),axes:a.axes})),r(this,"input-update",d))}});"use strict";
self.aa.fa(class extends self.ha{constructor(d){super(d,"mouse");C(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";async function ja(d,a){a=a.type;let b=!0;0===a?b=await ka():1===a&&(b=await la());r(d,"permission-result",{type:a,result:b})}
async function ka(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request orientation permission: ",d),!1}}
async function la(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(d){return console.warn("[Touch] Failed to request motion permission: ",d),!1}}self.aa.fa(class extends self.ha{constructor(d){super(d,"touch");C(this,"request-permission",a=>ja(this,a))}});"use strict";
async function ma(d){if(!d.Ea)try{d.Ea=await navigator.wakeLock.request("screen"),d.Ea.addEventListener("release",()=>{console.log("[Construct 3] Screen wake lock released");d.Ea=null;r(d,"wake-lock-released")}),console.log("[Construct 3] Screen wake lock acquired"),r(d,"wake-lock-acquired")}catch(a){console.warn("[Construct 3] Failed to acquire screen wake lock: ",a),r(d,"wake-lock-error")}}
function Y(){var d=document.body;const a=d.style;a.setProperty("--temp-sai-top","env(safe-area-inset-top)");a.setProperty("--temp-sai-right","env(safe-area-inset-right)");a.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");a.setProperty("--temp-sai-left","env(safe-area-inset-left)");d=getComputedStyle(d);d=[d.getPropertyValue("--temp-sai-top"),d.getPropertyValue("--temp-sai-right"),d.getPropertyValue("--temp-sai-bottom"),d.getPropertyValue("--temp-sai-left")].map(b=>{b=parseInt(b,10);
return isFinite(b)?b:0});a.removeProperty("--temp-sai-top");a.removeProperty("--temp-sai-right");a.removeProperty("--temp-sai-bottom");a.removeProperty("--temp-sai-left");return d}
self.aa.fa(class extends self.ha{constructor(d){super(d,"platform-info");F(this,[["get-initial-state",()=>this.Hc()],["request-wake-lock",()=>ma(this)],["release-wake-lock",()=>{this.Ea&&(this.Ea.release(),this.Ea=null)}]]);window.addEventListener("resize",()=>{r(this,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:Y()})});this.Ea=null}Hc(){return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,
safeAreaInset:Y(),supportsWakeLock:!!navigator.wakeLock}}});"use strict";
{function d(a){a.stopPropagation()}self.aa.fa(class extends self.De{constructor(a){super(a,"sliderbar")}nd(a,b){const c=document.createElement("input");c.type="range";c.style.position="absolute";c.style.userSelect="none";c.style.webkitUserSelect="none";c.addEventListener("touchstart",d);c.addEventListener("touchmove",d);c.addEventListener("touchend",d);c.addEventListener("mousedown",d);c.addEventListener("mouseup",d);c.addEventListener("keydown",d);c.addEventListener("keyup",d);c.addEventListener("click",
()=>{var g;g||(g={});g.elementId=a;z(this,"click",g)});c.addEventListener("change",()=>L(this,"change",a,{value:parseFloat(c.value)}));c.addEventListener("input",()=>L(this,"input",a,{value:parseFloat(c.value)}));b.id&&(c.id=b.id);this.uc(c,b);return c}uc(a,b){a.max=b.max;a.min=b.min;a.step=b.step;a.value=b.value;a.disabled=!b.isEnabled;a.title=b.title}})};
