BEAR_SEGWAY_GAME.EndScreen=function(game){BEAR_SEGWAY_GAME._game=game;};var spaceKey;BEAR_SEGWAY_GAME.EndScreen.prototype={create:function(){this.bg=this.add.tileSprite(0,0,BEAR_SEGWAY_GAME.GAME_WIDTH,BEAR_SEGWAY_GAME.GAME_HEIGHT,'backgroundSky');this.bg.fixedToCamera=true;this.bg2=this.add.tileSprite(0,170,BEAR_SEGWAY_GAME.GAME_WIDTH,300,'backgroundMountains');this.bg2.fixedToCamera=true;this.bg5=this.add.tileSprite(0,20,BEAR_SEGWAY_GAME.GAME_WIDTH,220,'backgroundSkyBits');this.bg5.fixedToCamera=true;this.bg5.autoScroll(-2,0);this.bg3=this.add.tileSprite(0,170,BEAR_SEGWAY_GAME.GAME_WIDTH,300,'backgroundTrees');this.bg3.fixedToCamera=true;BEAR_SEGWAY_GAME._fx=this.add.audio('sfx');BEAR_SEGWAY_GAME._fx.allowMultiple=true;BEAR_SEGWAY_GAME._fx.addMarker('click',0.5,0.5);BEAR_SEGWAY_GAME._fx.addMarker('crash',2.10,1.7);this.sound.mute=false;if(this.game.device.localStorage){if(localStorage.soundOn==1)this.sound.mute=false;else this.sound.mute=true;this.GOALSCOMPLETED=localStorage.getItem('bearGoalsCompleted');if(this.GOALSCOMPLETED==null)this.GOALSCOMPLETED=0;}
if(this.GOALSCOMPLETED<14)
{this._goalmarker=this.add.sprite((BEAR_SEGWAY_GAME.GoalItems[this.GOALSCOMPLETED].xPosition*100)+(BEAR_SEGWAY_GAME.GAME_WIDTH/2),300,'goalmarker');this._goalmarker.anchor.setTo(0.5);}
if(!this.sound.mute)
{this._buttonsound=this.add.button(BEAR_SEGWAY_GAME.GAME_WIDTH-170,20,'soundicon',this.muteSound,this,0,0,0);BEAR_SEGWAY_GAME._music=this.add.audio('music');BEAR_SEGWAY_GAME._music.allowMultiple=false;BEAR_SEGWAY_GAME._music.loop=true;BEAR_SEGWAY_GAME._music.play();}
else
{this._buttonsound=this.add.button(BEAR_SEGWAY_GAME.GAME_WIDTH-170,20,'soundicon',this.muteSound,this,1,1,1);BEAR_SEGWAY_GAME._music=this.add.audio('music');BEAR_SEGWAY_GAME._music.allowMultiple=false;BEAR_SEGWAY_GAME._music.loop=true;}
if(!this.sound.mute){BEAR_SEGWAY_GAME._fx.play('crash');}
this._buttonsound.freezeFrames=true;this._buttonsound.input.useHandCursor=true;this._buttonsound.fixedToCamera=true;this.bg4=this.add.tileSprite(0,440,BEAR_SEGWAY_GAME.GAME_WIDTH,200,'backgroundGround');this.bg4.fixedToCamera=true;this.gameoverScreen=this.add.sprite(BEAR_SEGWAY_GAME.GAME_WIDTH/2,300,'gameoverscreen');this.gameoverScreen.anchor.setTo(0.5);this.gameoverScreen.fixedToCamera=true;if(BEAR_SEGWAY_GAME.Score<0)BEAR_SEGWAY_GAME.Score=0;var tempScore=String(BEAR_SEGWAY_GAME.Score.toFixed(2));var tempScoreString=tempScore+" Meters";this._scoreLastText=this.add.bitmapText(BEAR_SEGWAY_GAME.GAME_WIDTH/2+30,250,'Junebug',tempScoreString,30);this._scoreLastText.anchor.setTo(0,0.5);this._scoreLastText.fixedToCamera=true;if(BEAR_SEGWAY_GAME.Score>BEAR_SEGWAY_GAME.HighScore)
{BEAR_SEGWAY_GAME.HighScore=BEAR_SEGWAY_GAME.Score;if(this.game.device.localStorage){localStorage.setItem('bearHighScore',BEAR_SEGWAY_GAME.HighScore);}
BEAR_SEGWAY_GAME.FlagPosition=BEAR_SEGWAY_GAME.HighScore*100;}
var tempHighScore=String(BEAR_SEGWAY_GAME.HighScore.toFixed(2));if(this.GOALSCOMPLETED<BEAR_SEGWAY_GAME.GoalItems.length)
{for(var i=0;i<BEAR_SEGWAY_GAME.GoalItems.length;i++){if(BEAR_SEGWAY_GAME.HighScore>BEAR_SEGWAY_GAME.GoalItems[i].xPosition)
{this.GOALSCOMPLETED=i+1;if(this.game.device.localStorage){localStorage.setItem('bearGoalsCompleted',this.GOALSCOMPLETED);}}}}
var tempHighScoreString=tempHighScore+" Meters";this._bestScoreText=this.add.bitmapText(BEAR_SEGWAY_GAME.GAME_WIDTH/2+30,315,'Junebug',tempHighScoreString,30);this._bestScoreText.anchor.setTo(0,0.5);this._bestScoreText.fixedToCamera=true;this._mainmenu=this.add.button(BEAR_SEGWAY_GAME.GAME_WIDTH/2-140,370,'menu-btn',this.restartGame,this,1,0,1);this._mainmenu.input.useHandCursor=true;this._mainmenu.fixedToCamera=true;this._replay=this.add.button(BEAR_SEGWAY_GAME.GAME_WIDTH/2+40,370,'restart_btn',this.resetGame,this,1,0,1);this._replay.input.useHandCursor=true;this._replay.fixedToCamera=true;spaceKey=this.input.keyboard.addKey(Phaser.Keyboard.SPACEBAR);this.input.keyboard.addKeyCapture([Phaser.Keyboard.SPACEBAR]);},muteSound:function(){if(!this.sound.mute){if(this.game.device.localStorage){localStorage.soundOn=0;}
this.sound.mute=true;this._buttonsound.frame=1;}
else{if(this.game.device.localStorage){localStorage.soundOn=1;}
this.sound.mute=false;this._buttonsound.frame=0;BEAR_SEGWAY_GAME._fx.play('click');BEAR_SEGWAY_GAME._music.play();}},update:function(){if(spaceKey.isDown)
{this.resetGame();}},pauseGame:function(){BEAR_SEGWAY_GAME._game._music.stop();BEAR_SEGWAY_GAME._game.paused=true;},resumeMainMenu:function(){BEAR_SEGWAY_GAME._game.paused=false;BEAR_SEGWAY_GAME._game.state.start("MainMenu");},resumePlayAgain:function(){BEAR_SEGWAY_GAME._game.paused=false;BEAR_SEGWAY_GAME._game.state.start('Game');},resetGame:function(){if(!this.sound.mute){BEAR_SEGWAY_GAME._fx.play('click');}
if(this.bg)this.bg.destroy();if(this.bg2)this.bg2.destroy();if(this.bg3)this.bg3.destroy();if(this.bg4)this.bg4.destroy();if(this._scoreText)this._scoreText.destroy();if(this._bestScoreText)this._bestScoreText.destroy();if(this._scoreLastText)this._scoreLastText.destroy();if(this._mainmenu)this._mainmenu.destroy();if(this.gameoverScreen)this.gameoverScreen.destroy();if(this._replay)this._replay.destroy();if(this.bg5)this.bg5.destroy();if(BEAR_SEGWAY_GAME._music)BEAR_SEGWAY_GAME._music.destroy();if(BEAR_SEGWAY_GAME._fx)BEAR_SEGWAY_GAME._fx.destroy();if(this._buttonsound)this._buttonsound.destroy();try{gameEventReplayTrigger();console.log("cmgGameEvent replay Called");}catch(err){console.log("cmgGameEvent Replay Function Not Found!");}
this.state.start('Game');},restartGame:function(){if(!this.sound.mute){BEAR_SEGWAY_GAME._fx.play('click');}
if(this.bg)this.bg.destroy();if(this.bg2)this.bg2.destroy();if(this.bg3)this.bg3.destroy();if(this.bg4)this.bg4.destroy();if(this._scoreText)this._scoreText.destroy();if(this._bestScoreText)this._bestScoreText.destroy();if(this._scoreLastText)this._scoreLastText.destroy();if(this._mainmenu)this._mainmenu.destroy();if(this.gameoverScreen)this.gameoverScreen.destroy();if(this._replay)this._replay.destroy();if(this.bg5)this.bg5.destroy();if(BEAR_SEGWAY_GAME._music)BEAR_SEGWAY_GAME._music.destroy();if(BEAR_SEGWAY_GAME._fx)BEAR_SEGWAY_GAME._fx.destroy();if(this._buttonsound)this._buttonsound.destroy();this.state.start('MainMenu');}};