BEAR_SEGWAY_GAME.Game=function(game){BEAR_SEGWAY_GAME._game=game;};var cursors;BEAR_SEGWAY_GAME.Game.prototype={create:function(){this.initialiseVars();this.physics.startSystem(Phaser.Physics.P2JS);this.physics.p2.gravity.y=this.GRAVITY;this.physics.p2.restitution=0;this._leaningleft=false;this._leaningright=false;BEAR_SEGWAY_GAME._fx=this.add.audio('sfx');BEAR_SEGWAY_GAME._fx.allowMultiple=true;BEAR_SEGWAY_GAME._fx.addMarker('click',0.5,0.5);BEAR_SEGWAY_GAME._fx.addMarker('fall',1.10,0.85);this.world.setBounds(0,0,999999,490);this.physics.arcade.setBoundsToWorld();this.bg=this.add.tileSprite(0,0,BEAR_SEGWAY_GAME.GAME_WIDTH,BEAR_SEGWAY_GAME.GAME_HEIGHT,'backgroundSky');this.bg.fixedToCamera=true;this.bg2=this.add.tileSprite(0,170,BEAR_SEGWAY_GAME.GAME_WIDTH,300,'backgroundMountains');this.bg2.fixedToCamera=true;this.bg5=this.add.tileSprite(0,20,BEAR_SEGWAY_GAME.GAME_WIDTH,220,'backgroundSkyBits');this.bg5.fixedToCamera=true;this.bg5.autoScroll(-2,0);this.bg3=this.add.tileSprite(0,170,BEAR_SEGWAY_GAME.GAME_WIDTH,300,'backgroundTrees');this.bg3.fixedToCamera=true;this.marker=this.add.sprite(BEAR_SEGWAY_GAME.FlagPosition+(BEAR_SEGWAY_GAME.GAME_WIDTH/2),435,'marker');this.marker.anchor.setTo(0.5);this.sprite1=this.add.sprite(BEAR_SEGWAY_GAME.GAME_WIDTH/2,460,'wheel');this.sprite1.anchor.setTo(0.5,0.5);this.bear=this.add.sprite(BEAR_SEGWAY_GAME.GAME_WIDTH/2,350,'bear');this.bear.animations.add('idle',[0,1,2,3],10,true,true);this.bear.animations.add('fall',[4,5,6,7],20,true,true);this.bear.animations.play('idle');this.bear.anchor.setTo(0.5,0);this.camera.follow(this.sprite1,Phaser.Camera.FOLLOW_LOCKON);this.physics.p2.enable([this.sprite1,this.bear],false);this.sprite1.body.clearCollision(true,true);this.bear.body.clearCollision(true,true);this.sprite1.body.setCircle(32);this.bear.body.setRectangle(60,200,0,-30);this.bear.body.mass=1.5;this.bearDead=false;var constraint=this.physics.p2.createRevoluteConstraint(this.sprite1,[0,0],this.bear,[0,110]);this.sprite1.body.collideWorldBounds=true;this.sprite1.body.maxAngular=this.MAX_SPEED;this.sprite1.body.angularDrag=this.DRAG;this.sprite1.alpha=0;this.sound.mute=false;if(this.game.device.localStorage){if(localStorage.soundOn==1)this.sound.mute=false;else this.sound.mute=true;this.GOALSCOMPLETED=localStorage.getItem('bearGoalsCompleted');if(this.GOALSCOMPLETED==null)this.GOALSCOMPLETED=0;}
if(this.GOALSCOMPLETED<BEAR_SEGWAY_GAME.GoalItems.length)
{this._goalmarker=this.add.sprite((BEAR_SEGWAY_GAME.GoalItems[this.GOALSCOMPLETED].xPosition*100)+(BEAR_SEGWAY_GAME.GAME_WIDTH/2),300,'goalmarker');this._goalmarker.anchor.setTo(0.5);}
if(!this.sound.mute)
{this._buttonsound=this.add.button(BEAR_SEGWAY_GAME.GAME_WIDTH-170,20,'soundicon',this.muteSound,this,0,0,0);BEAR_SEGWAY_GAME._music=this.add.audio('music');BEAR_SEGWAY_GAME._music.allowMultiple=false;BEAR_SEGWAY_GAME._music.loop=true;BEAR_SEGWAY_GAME._music.play();}
else
{this._buttonsound=this.add.button(BEAR_SEGWAY_GAME.GAME_WIDTH-170,20,'soundicon',this.muteSound,this,1,1,1);BEAR_SEGWAY_GAME._music=this.add.audio('music');BEAR_SEGWAY_GAME._music.allowMultiple=false;BEAR_SEGWAY_GAME._music.loop=true;}
this._buttonsound.freezeFrames=true;this._buttonsound.input.useHandCursor=true;this._buttonsound.fixedToCamera=true;if(!this.sound.mute){BEAR_SEGWAY_GAME._fx.play('fall');}
this.bg4=this.add.tileSprite(0,440,BEAR_SEGWAY_GAME.GAME_WIDTH,200,'backgroundGround');this.bg4.fixedToCamera=true;this.hud=this.add.sprite(BEAR_SEGWAY_GAME.GAME_WIDTH/2,BEAR_SEGWAY_GAME.GAME_HEIGHT-50,'hudcounter');this.hud.anchor.setTo(0.5,0.5);this.hud.fixedToCamera=true;this._leanleft=this.add.button(190,BEAR_SEGWAY_GAME.GAME_HEIGHT/2,'leanleft');this._leanleft.anchor.setTo(0.5,0.5);this._leanleft.fixedToCamera=true;this._leanleft.alpha=1;this._leanright=this.add.button(940,BEAR_SEGWAY_GAME.GAME_HEIGHT/2,'leanright');this._leanright.anchor.setTo(0.5,0.5);this._leanright.fixedToCamera=true;this._leanright.alpha=1;BEAR_SEGWAY_GAME.Score=0;this.firstPlay=0;var tempScore=String(BEAR_SEGWAY_GAME.Score/10);this._scoreText=this.add.bitmapText(BEAR_SEGWAY_GAME.GAME_WIDTH/2,BEAR_SEGWAY_GAME.GAME_HEIGHT-50,'Junebug',tempScore,40);this._scoreText.anchor.setTo(0.5);this._scoreText.fixedToCamera=true;if(this.GOALSCOMPLETED<BEAR_SEGWAY_GAME.GoalItems.length)
{this._goalDescription="GOAL: "+BEAR_SEGWAY_GAME.GoalItems[this.GOALSCOMPLETED].description;}
else this._goalDescription="HOW FAR CAN YOU GET?";this._goalText=this.add.bitmapText(BEAR_SEGWAY_GAME.GAME_WIDTH/2,80,'Junebug',this._goalDescription,50);this._goalText.anchor.setTo(0.5);this._goalText.fixedToCamera=false;this.bear.body.onBeginContact.add(this.fallen,this);cursors=this.input.keyboard.createCursorKeys();this._leanleft.events.onInputDown.add(function(){this._leaningleft=true;},this);this._leanright.events.onInputDown.add(function(){this._leaningright=true;},this);this._leanleft.events.onInputUp.add(function(){this._leaningleft=false;},this);this._leanright.events.onInputUp.add(function(){this._leaningright=false;},this);},initialiseVars:function(){this.ACCELERATION=500;this.MAX_SPEED=550;this.DRAG=200;this.GRAVITY=410;this.GOALSCOMPLETED=0;var GOAL1={name:'15',description:'REACH 15 METERS',xPosition:15};var GOAL2={name:'30',description:'REACH 30 METERS',xPosition:30};var GOAL3={name:'45',description:'REACH 45 METERS',xPosition:45};var GOAL4={name:'60',description:'REACH 60 METERS',xPosition:60};var GOAL5={name:'75',description:'REACH 75 METERS',xPosition:75};var GOAL6={name:'100',description:'REACH 100 METERS',xPosition:100};var GOAL7={name:'125',description:'REACH 125 METERS',xPosition:125};var GOAL8={name:'150',description:'REACH 150 METERS',xPosition:150};var GOAL9={name:'200',description:'REACH 200 METERS',xPosition:200};var GOAL10={name:'250',description:'REACH 250 METERS',xPosition:250};var GOAL11={name:'300',description:'REACH 300 METERS',xPosition:300};var GOAL12={name:'400',description:'REACH 400 METERS',xPosition:400};var GOAL13={name:'500',description:'REACH 500 METERS',xPosition:500};var GOAL14={name:'1000',description:'REACH 1000 METERS',xPosition:1000};BEAR_SEGWAY_GAME.GoalItems=[GOAL1,GOAL2,GOAL3,GOAL4,GOAL5,GOAL6,GOAL7,GOAL8,GOAL9,GOAL10,GOAL11,GOAL12,GOAL13,GOAL14];},fallen:function(body,bodyB,shapeA,shapeB,equation){if(body)
{}
else{if(!this.bearDead)this.bearDead=true;this.endTheGame();}},endTheGame:function(){this.endGame();},muteSound:function(){if(!this.sound.mute){if(this.game.device.localStorage){localStorage.soundOn=0;}
this.sound.mute=true;this._buttonsound.frame=1;}
else{if(this.game.device.localStorage){localStorage.soundOn=1;}
this.sound.mute=false;this._buttonsound.frame=0;BEAR_SEGWAY_GAME._fx.play('click');BEAR_SEGWAY_GAME._music.play();}},tweenOutTutorial:function(){var tween1=this.add.tween(this._leanleft).to({alpha:0},1000,"Linear",true);var tween2=this.add.tween(this._leanright).to({alpha:0},1000,"Linear",true);},update:function(){if(!this.bearDead)
{this.sprite1.body.rotateleft=0;this.sprite1.body.force.x=0;if(this.bear.angle>12||this.bear.angle<-12)this.bear.animations.play('fall');else this.bear.animations.play('idle');if(cursors.left.isDown||this._leaningleft)
{this.firstPlay++;this.sprite1.body.force.x-=this.ACCELERATION;this.sprite1.body.rotateleft-=2;}
else if(cursors.right.isDown||this._leaningright)
{this.firstPlay++;this.sprite1.body.force.x+=this.ACCELERATION;this.sprite1.body.rotateRight-=2;}
if(this.firstPlay==1){this.tweenOutTutorial();}
var cx=this.camera.x;var cy=this.camera.y;this.bg.tilePosition.set(cx*-0.1,cy*-0.1);this.bg2.tilePosition.set(cx*-0.2,cy*-0.2);this.bg3.tilePosition.set(cx*-0.45,cy*-0.45);this.bg4.tilePosition.set(cx*-0.55,cy*-0.4);BEAR_SEGWAY_GAME.Score=Phaser.Math.roundTo((this.sprite1.body.x-BEAR_SEGWAY_GAME.GAME_WIDTH/2)/100,-2);if(BEAR_SEGWAY_GAME.Score>0)
{this._scoreText.setText(BEAR_SEGWAY_GAME.Score.toFixed(2));}
else{this._scoreText.setText("0.00");}}},endGame:function(){if(this._goalmarker)this._goalmarker.destroy();if(this.marker)this.marker.destroy();this.bg.destroy();this.bg2.destroy();this.bg3.destroy();this.bg4.destroy();this._scoreText.destroy();this.bg5.destroy();this._leaningleft=false;if(this._leanleft)this._leanleft.destroy();if(this._leanright)this._leanright.destroy();this.hud.destroy();this._leaningright=false;this._goalText.destroy();this.sprite1.destroy();this.bear.destroy();this.physics.p2.clear();if(BEAR_SEGWAY_GAME._music)BEAR_SEGWAY_GAME._music.destroy();if(BEAR_SEGWAY_GAME._fx)BEAR_SEGWAY_GAME._fx.destroy();if(this._buttonsound)this._buttonsound.destroy();cursors=null;this.state.start('End');},};