var cpmstar_anchorad_settings=cpmstar_anchorad_settings||{},create_cpmstar_anchorad=function(a){function x(b){if(b||!C&&!v)b=-1*a.slideDistance+"px",q.isIOS()?q.setAnimationStyle(f,"Transform","translate(0px,"+b+")"):f.style[r]=b,v=!0}var q=function(){var a=["webkit","Moz","O","ms","Khtml"];return{setAnimationStyle:function(b,g,f){for(var d=!1,e=0;e<a.length;e++)if(void 0!==b.style[a[e]+g]){b.style[a[e]+g]=f;d=!0;break}return d},setCSSStyle:function(a,b,f){var d=!1;try{void 0!==a.style[b]&&(a.style[b]=
f,d=!0)}catch(e){d=!1}return d},ieVersion:function(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return a},isIOS:function(){var a=!1;if(navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPhone/i))a=!0;return a}}}(),D,G=function(){D=setInterval(function(){a.d.getElementsByTagName("body")[0]&&(clearInterval(D),A())},10)},B=function(){v&&(f.style.color="#FFF",q.setAnimationStyle(f,"Transition",
"2s ease"),q.isIOS()?q.setAnimationStyle(f,"Transform","translate(0px,0px)"):f.style[r]="0px",v=!1)},z=function(){var b;void 0!=m.contentDocument&&void 0!=m.contentDocument.body?b=m.contentDocument.body:t&&(b=t);if(void 0!=b){for(var d=b.getElementsByTagName("object"),g=b.getElementsByTagName("img"),n=b.getElementsByTagName("iframe"),l=b.getElementsByTagName("div"),e=0,h=0,c=0;c<d.length;c++)d[c].height>e&&(e=d[c].height),d[c].width>h&&(h=d[c].width);for(c=0;c<g.length;c++)g[c].height>e&&(e=g[c].height),
g[c].width>h&&(h=g[c].width);for(c=0;c<n.length;c++)n[c].height>e&&(e=n[c].height),n[c].width>h&&(h=n[c].width);for(c=0;c<n.length;c++)n[c].height>e&&(e=n[c].height),n[c].width>h&&(h=n[c].width);for(c=0;c<l.length;c++){g=d=0;try{d=parseInt(l[c].style.height),g=parseInt(l[c].style.width)}catch(I){}d>e&&(e=d);g>h&&(h=g);l[c].innerHeight>e&&(e=l[c].clientHeight);l[c].innerWidth>h&&(h=l[c].clientWidth)}if(0===e){a:if(b.classList&&b.classList.contains&&0<b.classList.contains("cpmstar_googlead"))b=!0;else{b=
b.getElementsByTagName("script");for(l=0;l<b.length;l++)if(0<=b[l].src.indexOf("//pagead2.googlesyndication.com/pagead/show_ads.js")){b=!0;break a}b=!1}b&&(e=90,0===h&&(h=728))}a.slideDistance="height"==y?e:h;m.height=e;m.width=h}0<a.slideDistance?(p.style[r]=a.slideDistance-26+"px",k.style[r]=a.slideDistance-36+"px"):(p.style[r]="0px",k.style[r]="0px");p.style.backgroundColor=a.bgColorBase;q.setCSSStyle(p,"opacity","0.25")||q.setCSSStyle(p,"filter","alpha(opacity=25)");q.setAnimationStyle(f,"Transition",
"all 2s ease");x()},t,m,f,p,k,C=!1,v=!1,E="bottom",r="top",y="height",w="width",u="left",F=function(a){a=a.toString();return"%"==a.slice(a.length-1)?"%":"px"==a.slice(a.length-2)?"px":""},H=function(){var b=a.el==a.d.getElementsByTagName("body")[0];b||"static"!=getComputedStyle(a.el).position||(a.el.style.position="relative",a.el.style.overflow="hidden");var d=a.d.createElement("div");d.name="cpmstar_anchor";d.style.zIndex="2147483647";d.style.position=b?"fixed":"absolute";d.style[w]="100%";d.style[E]=
"0px";d.style[u]="0px";b=a.d.createElement("div");b.name="cpmstar_anchor_container";b.style.position="relative";b.style.width="100%";b.style.height="100%";f=a.d.createElement("div");f.name="cpmstar_anchor_slide";f.style.position="absolute";-1!=a.dir&&(f.style[y]="0px");f.style[r]="0px";a.closeBarSize?(f.style["margin"+u.charAt(0).toUpperCase()+u.substr(1)]=-Math.round(parseFloat(a.closeBarSize)/2)+("%"==F(a.closeBarSize)?"%":"px"),f.style[u]="50%",f.style[w]=Math.round(parseFloat(a.closeBarSize))+
("%"==F(a.closeBarSize)?"%":"px")):(f.style[u]="0px",f.style[w]="100%");f.style.backgroundColor="Transparent";var g=a.d.createElement("div");g.name="cpmstar_anchor_ad";g.style.backgroundColor="Transparent";g.style.position="absolute";g.style.zIndex="2147483647";a.horizontal?(g.style.top="50%",g.style.transform="translate(0, -50%)"):(g.style.left="50%",g.style.transform="translate(-50%, 0)");g.style[r]="0px";var n=a.d.createElement("div");n.style.position="relative";n.style.zIndex="2147483647";m=a.d.createElement("iframe");
m.name="cpmstar_anchor_ifrad";m.scrolling="no";m.frameBorder=0;m.marginHeight=0;m.marginWidth=0;t=a.d.createElement("div");t.id=a.divid;p=a.d.createElement("div");p.name="cpmstar_anchor_close";p.style.position="absolute";p.style[r]="30px";p.style[y]="30px";p.style[w]="100%";p.style[u]="0px";p.style.backgroundColor=a.bgColorBase;var l=a.d.createElement("div");7==q.ieVersion()||8==q.ieVersion()?l.style.styleFloat="right":l.style.cssFloat="right";l.style.position="relative";l.style.zIndex="2147483647";
var e=a.d.createElement("a");e.href="#";e.onclick="";e.style.color="black";k=a.d.createElement("img");k.src=("https:"==a.d.location.protocol?"https://ssl.cdne":"http://cdn")+".cpmstar.com/cached/x.png";k.name="cpmstar_anchor_close_button";k.alt="Close Ad";k.style.borderWidth="0px";k.style.position="absolute";k.style.zIndex="2147483647";k.style.right="5px";k.style.margin="10px";k.style.cursor="pointer";k.style.verticalAlign="middle";k.style["min-width"]="24px";k.style["min-height"]="24px";k.style.width=
"24px";k.style.height="24px";k.style.visibility="visible";k.style.display="block";var h=a.d.createElement("div");h.onclick=function(){C=!0;B();a.triggerEvent&&a.triggerEvent("onclose");return!1};h.appendChild(k);n.appendChild(t);g.appendChild(n);l.appendChild(e);p.appendChild(l);f.appendChild(g);f.appendChild(p);f.appendChild(h);b.appendChild(f);d.appendChild(b);a.el.appendChild(d)},A=function(){H();var b=a.renderAd;if(b)b(t),z(),a.triggerEvent&&a.triggerEvent("onready");else{b='<script type="text/javascript">function adloaded(){var chkRdyInterval;var chkBodyRdy = function(){if(document.getElementsByTagName(\'body\')[0]){clearInterval(chkRdyInterval);cpmstar_anchorad.anchorReady();}};var adReady = function(){chkRdyInterval = setInterval(function(){chkBodyRdy();}, 10);};adReady();}function ieLoadBugFix(scriptElement, callback){if(scriptElement.readyState == "loaded" || scriptElement.readyState == "complete"){callback();}else{setTimeout(function (){ ieLoadBugFix(scriptElement, callback); }, 100);}}\x3c/script><script type="text/javascript" id=\'adscript\' name=\'adscript\' src="'+
("https:"==window.location.protocol?"https:":"http:")+"//server.cpmstar.com/view.aspx?poolid="+a.poolid+"&subpoolid="+a.subpoolid+"&script=1&rnd="+Math.round(999999*Math.random())+"\" onload='adloaded();'>\x3c/script>";if(7==q.ieVersion()||8==q.ieVersion())b+="<script type=\"text/javascript\">var s = document.getElementById('adscript');ieLoadBugFix(s, function(){ adloaded(); });\x3c/script>";m.parentNode||cpmstar_anchor_ad_inner.appendChild(m);var d=m.contentWindow.document;(m.contentWindow||m.contentDocument.defaultView).cpmstar_anchorad=
cpmstar_anchorad;d.open();d.write(b);(10<=q.ieVersion()||-1==q.ieVersion())&&d.close()}};a.manualInit||(a.el?a.d=a.el.ownerDocument:(a.d=a.d||document,a.el=a.d.getElementsByTagName("body")[0]),a={poolid:a.poolid,subpoolid:a.subpoolid||0,d:a.d,el:a.el,divid:a.divid||"cpmstar_anchor_divad",bgColorBase:a.bgColorBase||"black",closeBarSize:a.width||a.closeBarSize,slideDistance:a.height||a.slideDistance||0,dir:a.dir||1,horizontal:a.horizontal||!1,renderAd:a.renderAd,triggerEvent:a.triggerEvent,manualInit:a.manualInit},
E=a.horizontal?1==a.dir?"right":"left":1==a.dir?"bottom":"top",r=a.horizontal?1!=a.dir?"right":"left":1!=a.dir?"bottom":"top",y=a.horizontal?"width":"height",w=a.horizontal?"height":"width",u=a.horizontal?"top":"left",G());return{initAd:function(){A()},anchorReady:function(){z()},showAnchor:function(){x(!0)},hideAnchor:function(){B()},adcmd:function(b){({init:A,ready:z,show:function(){x(!0)},hide:B,refresh:function(){a.renderAd=b.renderFn;var d=t;d.innerHTML="";b.renderFn(d);z();v&&x(!0)}})[b.command].apply(this,
b.args)}}},cpmstar_anchorad=create_cpmstar_anchorad(cpmstar_anchorad_settings);
